# Preface {.unnumbered}

This notebook was created to host learning materials for Math 130: Introduction to R at California State University, Chico.

Some of this material presented is a derivation from work that is Copyright © Software Carpentry (http://software-carpentry.org/) which is under a [CC BY 4.0 license](https://creativecommons.org/licenses/by/4.0/) which allows for adaptations and reuse of the work.

Math 130 is designed as a short-course "primer" to be taken before, or concurrently with, an upper division or graduate level Statistics course such as Math 315 or Math 615. This can also be used a prepratory learning for classified admission into the [Masters in Data Science and Analytics Program](https://www.csuchico.edu/math/degrees/msdsa.shtml)

The goal of Math 130 is to get the complete novice up and running with the basic knowledge of how to use the statistical programming language R in an environment that emphasizes reproducible research and literate programming for data analysis. We recognize there are many topics and many approaches to teach an introduction to the R programming language. We have picked specific topics and methods that we believe learners will need to succeed in subsequent classes.



::: {.callout-note title="Course Learning Objectives"}
By the end of this class you will be able to: 

* Import spreadsheet-like data into R from an external file
* Perform basic data wrangling like handling missing values, creating new variables, labeling categorical variables, and filtering rows. 
* Create statistical data visualizations such as barcharts, histograms, boxplots, scatterplots, and extend to multivariate data by modifying colors, sizes, and panels. 
* Create statistical data summaries such as tables, proportions, and summary statistics. 
* Perform all of this work in a reproducible manner using professional tools. 

:::

## References & Acknowledgements

The material in the first section "Getting Started" is based heavily off of, and sometimes used directly, from the [Data Carpentry: R for Social Scientists](https://datacarpentry.github.io/r-socialsci/index.html) which is CC-BY 4.0.

