<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="NAME">

<title>Homework 1</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="_hw1_solutions_files/libs/clipboard/clipboard.min.js"></script>
<script src="_hw1_solutions_files/libs/quarto-html/quarto.js"></script>
<script src="_hw1_solutions_files/libs/quarto-html/popper.min.js"></script>
<script src="_hw1_solutions_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="_hw1_solutions_files/libs/quarto-html/anchor.min.js"></script>
<link href="_hw1_solutions_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="_hw1_solutions_files/libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="_hw1_solutions_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="_hw1_solutions_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="_hw1_solutions_files/libs/bootstrap/bootstrap-c0367b04c37547644fece4185067e4a7.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Homework 1</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>NAME </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">Invalid Date</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>Here’s your chance to demonstrate that you can integrate the topics and skills you learned so far into a literate report.</p>
<p>When the question asks you to perform a coding task, insert a code chunk after each question where you will write the code to answer that question. Knitting after each completed code chunk will help you to ensure your final product works as intended! That way if it breaks, you know exactly where the error lies. It’s like saving after every answer!</p>
<p>The first question is done for you as an example.</p>
<section id="object-assignments" class="level1">
<h1>Object assignments</h1>
<ol start="0" type="1">
<li>Calculate 3 + 4. Put the answer in the grey area below and knit the document. Make sure you can find this code and output in the resulting HTML file.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="dv">3</span><span class="sc">+</span><span class="dv">4</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 7</code></pre>
</div>
</div>
<ol type="1">
<li>Calculate <span class="math inline">\(2^5\)</span> by typing this mathematical expression in the code chunk below and then knit the document.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span><span class="sc">^</span><span class="dv">5</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 32</code></pre>
</div>
</div>
<ol start="2" type="1">
<li>What are the values after each statement in the following?</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>(mass <span class="ot">&lt;-</span> <span class="fl">47.5</span>)            <span class="co"># a </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 47.5</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>(age  <span class="ot">&lt;-</span> <span class="dv">122</span> )            <span class="co"># b</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 122</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>(mass <span class="ot">&lt;-</span> mass <span class="sc">*</span> <span class="fl">2.0</span>)      <span class="co"># c </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 95</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>(age  <span class="ot">&lt;-</span> age <span class="sc">-</span> <span class="dv">20</span>)        <span class="co"># d</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 102</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>(mass_index <span class="ot">&lt;-</span> mass<span class="sc">/</span>age)  <span class="co"># e</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9313725</code></pre>
</div>
</div>
<ol type="a">
<li><code>mass</code> = 47.5</li>
<li><code>age</code> = 122</li>
<li><code>mass</code> = 95</li>
<li><code>age</code> = 102</li>
<li><code>mass_index</code> = 0.9313725</li>
</ol>
<ol start="3" type="1">
<li>Assign a numeric value to the variable <code>my_apples</code>, assign a different numeric value to the variable <code>my_oranges</code>. Add these two together and assign the result to the variable <code>my_fruit</code>. Print the result of <code>my_fruit</code> to the report.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>my_apples <span class="ot">&lt;-</span> <span class="dv">6</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>my_oranges <span class="ot">&lt;-</span> <span class="dv">19</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>my_fruit <span class="ot">&lt;-</span> my_apples <span class="sc">+</span> my_oranges</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>my_fruit</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 25</code></pre>
</div>
</div>
<ol start="4" type="1">
<li>What is the data type of the variable <code>my_fruit</code>?</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(my_fruit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "numeric"</code></pre>
</div>
</div>
<p>Its class is “numeric”</p>
<ol start="5" type="1">
<li>A variable that classified as <code>logical</code> can hold only what two values? These are also called Boolean variables. (You don’t need to write code to answer this question.)</li>
</ol>
<p>TRUE and FALSE</p>
<ol start="6" type="1">
<li>Knit this document.</li>
</ol>
</section>
<section id="vectors" class="level1">
<h1>Vectors()</h1>
<ol type="1">
<li>Use the <code>class()</code> function to explore what happens when you have vectors of different data types. The first one has been done for you. Report your answer for each in a sentence below.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>num_only <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>)                    <span class="co">#a</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>char_only <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"a"</span>,<span class="st">"b"</span>,<span class="st">"c"</span>,<span class="st">"d"</span>)           <span class="co">#b</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>num_char <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="st">"a"</span>)               <span class="co">#c</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>num_logical <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="cn">TRUE</span>)           <span class="co">#d</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>char_logical <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"a"</span>, <span class="st">"b"</span>, <span class="st">"c"</span>, <span class="cn">TRUE</span>)    <span class="co">#e</span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>tricky <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="st">"4"</span>)                 <span class="co">#f</span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(num_only) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "numeric"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(char_only)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "character"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(num_char)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "character"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(num_logical)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "numeric"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(char_logical)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "character"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(tricky)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "character"</code></pre>
</div>
</div>
<ul>
<li><ol type="a">
<li>The <code>num_only</code> vector contains only numeric values, and it’s class is numeric.</li>
</ol></li>
<li><ol start="2" type="a">
<li>The <code>char_only</code> vector contains only character values, and it’s class is character.</li>
</ol></li>
<li><ol start="3" type="a">
<li>The <code>num_char</code> vector contains numeric and character values, and it’s class is character.</li>
</ol></li>
<li><ol start="4" type="a">
<li>The <code>num_logical</code> vector contains numeric and Boolean values, and it’s class is numeric.</li>
</ol></li>
<li><ol start="5" type="a">
<li>The <code>char_logical</code> vector contains character and Boolean values, and it’s class is character.</li>
</ol></li>
<li><ol start="6" type="a">
<li>The <code>tricky</code> vector contains three numeric value and one character value(“4”), and it’s class is character.</li>
</ol></li>
</ul>
<section id="lets-go-to-vegas" class="level2">
<h2 class="anchored" data-anchor-id="lets-go-to-vegas">Let’s go to Vegas!</h2>
<ol start="2" type="1">
<li>Create three vectors (<code>weekday</code>, <code>poker</code>, <code>roulette</code>) using the <code>c()</code> operator to describe the following outcome.</li>
</ol>
<ul>
<li><code>weekday</code>: The 5 weekdays. Use these three letter codes: “mon”, “tue”, “wed”, “thu”, “fri.”</li>
<li><code>poker</code>:
<ul>
<li>On Monday you won $140</li>
<li>Tuesday you lost $50</li>
<li>Wednesday you won $20</li>
<li>Thursday you lost $120</li>
<li>Friday you won $240</li>
</ul></li>
<li><code>roulette</code>:
<ul>
<li>On Monday you lost $24</li>
<li>Tuesday you lost $50</li>
<li>Wednesday you won $100</li>
<li>Thursday you lost $350</li>
<li>Friday you won $10</li>
</ul></li>
</ul>
<p><em>Hint: If I won $30 on monday and lost $20 on tuesday, my vector would look like <code>c(30, -20)</code></em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>weekday <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"mon"</span>, <span class="st">"tue"</span>, <span class="st">"wed"</span>, <span class="st">"thu"</span>, <span class="st">"fri"</span>)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>poker <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">140</span>, <span class="sc">-</span><span class="dv">50</span>, <span class="dv">20</span>, <span class="sc">-</span><span class="dv">120</span>, <span class="dv">240</span>)</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>roulette <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">24</span>, <span class="sc">-</span><span class="dv">50</span>, <span class="dv">100</span>, <span class="sc">-</span><span class="dv">350</span>, <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="3" type="1">
<li>Use the <code>sum()</code> function to calculate how much money did you gain/lose on each game. What game did you do better on?</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(poker)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 230</code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(roulette)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -314</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(poker) <span class="sc">&gt;</span> <span class="fu">sum</span>(roulette)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
<ul>
<li>We gained <code>$230</code> on poker and lost <code>$314</code> on roulette. We did better on poker game.</li>
</ul>
<ol start="4" type="1">
<li>Add the results of both vectors together, then calculate your net gain over the weekend. Did you come out ahead?</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(poker<span class="sc">+</span>roulette)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -84</code></pre>
</div>
</div>
<p>We came out behind.</p>
<ol start="5" type="1">
<li>On which days did you make money on poker? <em>Hint: subset the <code>weekday</code> vector using a logical statement about <code>poker</code></em></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>weekday[poker<span class="sc">&gt;</span><span class="dv">0</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "mon" "wed" "fri"</code></pre>
</div>
</div>
<ol start="6" type="1">
<li>On which days did you do better on poker than roulette? <em>Hint: compare the two vectors using a statement of inequality</em></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>weekday[poker <span class="sc">&gt;</span> roulette]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "mon" "thu" "fri"</code></pre>
</div>
</div>
<ol start="7" type="1">
<li>Knit this document to make sure it still works.</li>
</ol>
</section>
</section>
<section id="data-frames" class="level1">
<h1>Data Frames</h1>
<p>Run the code chunk below to read in the Ames data set from the web. This data set is on all residential home sales in Ames, Iowa between 2006 and 2010. The data set contains many explanatory variables on the quality and quantity of physical attributes of residential homes in Iowa sold between 2006 and 2010. Most of the variables describe information a typical home buyer would like to know about a property (square footage, number of bedrooms and bathrooms, size of lot, etc.). A detailed discussion of variables can be found in the original paper: De Cock D. 2011. Ames, Iowa: Alternative to the Boston Housing Data as an End of Semester Regression Project. Journal of Statistics Education; 19(3).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>ames <span class="ot">&lt;-</span> openintro<span class="sc">::</span>ames</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(ames)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 82
  Order      PID  area  price MS.SubClass MS.Zoning Lot.Frontage Lot.Area Street
  &lt;int&gt;    &lt;int&gt; &lt;int&gt;  &lt;int&gt;       &lt;int&gt; &lt;fct&gt;            &lt;int&gt;    &lt;int&gt; &lt;fct&gt; 
1     1   5.26e8  1656 215000          20 RL                 141    31770 Pave  
2     2   5.26e8   896 105000          20 RH                  80    11622 Pave  
3     3   5.26e8  1329 172000          20 RL                  81    14267 Pave  
4     4   5.26e8  2110 244000          20 RL                  93    11160 Pave  
5     5   5.27e8  1629 189900          60 RL                  74    13830 Pave  
6     6   5.27e8  1604 195500          60 RL                  78     9978 Pave  
# ℹ 73 more variables: Alley &lt;fct&gt;, Lot.Shape &lt;fct&gt;, Land.Contour &lt;fct&gt;,
#   Utilities &lt;fct&gt;, Lot.Config &lt;fct&gt;, Land.Slope &lt;fct&gt;, Neighborhood &lt;fct&gt;,
#   Condition.1 &lt;fct&gt;, Condition.2 &lt;fct&gt;, Bldg.Type &lt;fct&gt;, House.Style &lt;fct&gt;,
#   Overall.Qual &lt;int&gt;, Overall.Cond &lt;int&gt;, Year.Built &lt;int&gt;,
#   Year.Remod.Add &lt;int&gt;, Roof.Style &lt;fct&gt;, Roof.Matl &lt;fct&gt;,
#   Exterior.1st &lt;fct&gt;, Exterior.2nd &lt;fct&gt;, Mas.Vnr.Type &lt;fct&gt;,
#   Mas.Vnr.Area &lt;int&gt;, Exter.Qual &lt;fct&gt;, Exter.Cond &lt;fct&gt;, Foundation &lt;fct&gt;, …</code></pre>
</div>
</div>
<ol type="1">
<li>List out the variable name and data types for five different variables in the ames data set</li>
</ol>
<p>Order, integer PID, integer MS. Subclass, integer MS. Zoning, character Lot. Frontage, integer</p>
<ol start="2" type="1">
<li>How many observations does the ames data set have? How many variables?</li>
</ol>
<p>2930 observations and 82 variables.</p>
<ol start="3" type="1">
<li>Extract the variable that measures the overall condition of the house (<code>Overall.Cond</code>) by position (using bracket index notation <code>[]</code>), and by variable names (using <code>$</code> notation)</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>ames[,<span class="dv">22</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2,930 × 1
   Overall.Cond
          &lt;int&gt;
 1            5
 2            6
 3            6
 4            5
 5            5
 6            6
 7            5
 8            5
 9            5
10            5
# ℹ 2,920 more rows</code></pre>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>ames<span class="sc">$</span>Overall.Cond</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   [1] 5 6 6 5 5 6 5 5 5 5 5 7 5 5 5 5 7 2 5 6 6 6 5 7 6 6 5 5 5 5 5 5 5 6 6 5 5
  [38] 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 7 5 5 5 5 5 5 5 5 5 5
  [75] 5 5 5 5 5 7 5 6 5 5 7 8 5 5 8 6 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 6 8 5 6
 [112] 5 7 5 5 7 6 5 5 5 5 6 5 7 7 6 6 7 6 7 2 5 6 6 8 5 5 6 5 5 5 5 6 6 5 5 5 5
 [149] 5 7 6 5 7 7 7 7 7 5 5 7 7 8 7 4 7 6 6 7 5 5 7 7 6 7 6 6 7 7 7 7 6 2 8 9 6
 [186] 9 3 7 7 6 7 6 7 7 7 6 6 7 7 5 5 6 5 8 8 5 5 9 7 5 3 4 5 1 7 8 3 5 4 6 5 8
 [223] 7 7 5 5 5 5 5 7 4 7 6 5 4 5 7 6 6 7 5 5 3 7 5 5 7 5 6 5 5 5 5 5 8 7 5 5 5
 [260] 8 7 6 6 5 5 6 5 5 5 5 5 5 5 6 6 5 6 5 6 5 5 5 4 4 6 6 4 3 6 6 6 2 7 6 6 9
 [297] 8 6 6 5 8 8 5 5 4 7 5 7 5 5 7 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 6 3 7 6 4 6
 [334] 7 7 7 2 5 5 5 5 5 5 7 5 5 5 5 5 5 5 5 5 5 5 5 7 8 5 5 5 5 6 5 5 5 5 5 5 6
 [371] 7 5 5 7 6 6 7 5 5 5 5 5 7 5 5 5 5 7 6 5 5 6 5 6 8 5 7 6 6 7 6 7 5 6 5 6 8
 [408] 7 6 5 6 5 5 5 5 6 5 6 5 7 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
 [445] 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
 [482] 5 5 5 5 5 5 5 5 5 5 5 5 6 5 5 5 5 5 5 5 5 5 5 7 6 5 5 5 5 5 5 5 5 5 5 5 5
 [519] 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 6 5 5 5 5 5 5 5 5 5 5 5 5 6 6 5 5 7 7 4 3 5
 [556] 6 6 5 5 8 6 5 6 8 8 5 5 5 5 5 5 5 5 5 9 5 5 5 4 6 6 7 6 6 6 7 5 5 5 7 5 5
 [593] 6 6 5 6 5 5 5 7 7 6 5 6 5 6 6 5 6 6 6 6 6 5 7 4 4 5 5 6 8 7 5 6 5 8 6 6 3
 [630] 4 7 3 6 8 6 7 5 5 5 5 6 4 7 6 5 5 7 6 8 5 5 7 6 6 5 7 7 8 8 7 5 9 5 6 7 5
 [667] 5 7 4 5 9 6 7 5 6 7 4 5 5 4 6 6 7 5 5 7 7 5 7 6 5 8 6 8 5 6 8 8 6 4 6 5 8
 [704] 5 4 7 4 6 4 6 8 8 5 4 7 5 7 7 7 9 3 9 4 6 6 7 5 3 6 6 7 7 6 6 9 8 6 5 7 5
 [741] 6 7 3 7 6 6 5 6 8 6 8 8 6 1 5 5 7 5 6 6 7 9 5 5 5 1 6 3 6 6 5 6 7 5 5 6 5
 [778] 5 5 5 2 5 8 6 5 5 5 5 5 5 3 7 6 6 3 5 4 5 5 6 5 8 7 5 5 5 7 5 5 5 5 5 5 5
 [815] 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 7 5 6 5 5 5 5 5 5 5 5 5 5 5 5
 [852] 5 5 5 7 7 8 7 6 5 8 7 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 7 6 5
 [889] 6 6 6 5 5 9 5 5 3 8 3 5 5 3 8 6 5 4 5 5 7 3 6 3 8 6 9 6 7 8 9 6 7 7 4 7 6
 [926] 6 6 7 6 7 8 5 6 6 6 6 6 9 9 7 6 5 2 6 5 4 5 5 5 5 6 7 5 5 5 6 5 5 5 5 5 5
 [963] 5 8 5 5 5 5 5 7 4 5 5 5 6 8 5 4 6 4 8 5 6 5 6 5 5 5 7 8 7 5 5 5 5 5 5 5 5
[1000] 5 5 5 5 5 5 5 5 5 5 5 5 5 5 2 5 5 6 6 6 7 5 5 7 5 6 6 6 7 5 5 6 6 5 5 8 6
[1037] 5 5 5 5 5 6 6 5 3 5 6 6 6 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
[1074] 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 6 5 5 5 5 5 5 5 5 5 5 5 5 7 6 5 5 5 5
[1111] 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 6 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
[1148] 5 5 5 6 8 5 5 8 5 4 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 6 3 9
[1185] 5 6 6 5 7 7 6 7 6 8 7 5 5 5 6 9 6 8 9 5 5 6 7 6 5 7 6 7 8 5 5 7 6 5 7 6 6
[1222] 6 7 6 5 8 6 5 6 5 6 9 5 7 7 5 7 4 7 6 6 5 5 7 5 6 6 5 5 7 5 3 5 5 6 8 6 7
[1259] 5 7 6 6 7 5 6 7 7 7 5 5 6 5 6 6 7 6 5 5 6 7 5 6 5 5 5 8 7 5 7 4 7 6 5 6 5
[1296] 6 6 6 9 5 7 6 5 6 7 1 9 5 8 8 5 7 5 5 9 9 7 6 5 7 9 1 7 6 5 5 6 7 7 6 5 6
[1333] 7 9 7 7 7 7 5 7 7 7 7 6 7 5 5 5 8 6 5 7 6 4 5 7 8 7 8 6 6 6 6 7 6 7 7 7 8
[1370] 3 7 6 5 5 4 7 6 5 5 7 7 7 8 5 5 4 4 3 6 8 8 5 7 6 8 3 7 8 5 5 6 7 6 7 5 5
[1407] 8 7 7 7 6 5 8 8 7 5 5 6 5 5 5 5 5 5 5 5 5 5 5 6 5 7 6 5 5 5 5 5 5 5 5 5 5
[1444] 5 6 8 6 6 6 6 6 7 7 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 6 5
[1481] 5 5 5 5 5 7 7 5 6 5 6 6 5 5 6 7 5 7 5 5 5 5 4 5 5 7 8 5 6 6 7 6 7 6 3 6 8
[1518] 8 5 8 6 6 7 6 7 7 6 5 9 5 3 6 7 6 4 5 6 9 9 9 5 7 6 6 8 8 4 8 6 7 5 7 5 5
[1555] 7 4 7 4 6 5 5 5 5 5 5 5 6 6 4 5 6 6 6 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
[1592] 5 5 6 6 7 7 6 6 9 7 5 7 5 9 8 6 7 6 4 1 6 5 6 6 5 5 6 5 5 5 5 5 5 5 5 5 5
[1629] 5 5 6 5 5 5 5 5 5 5 5 5 6 5 5 7 5 7 7 6 5 6 6 6 6 6 5 5 5 6 6 7 6 6 7 5 9
[1666] 6 5 5 5 6 7 6 5 5 5 6 5 5 5 5 5 6 7 6 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
[1703] 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
[1740] 5 6 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 6 5 5 5 5 5 5 5 6
[1777] 5 5 5 5 5 5 5 5 5 6 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 6 5 5 5 5 5 5 5 5 5 5 5
[1814] 5 5 5 7 5 5 6 5 7 5 5 7 5 6 5 7 5 5 7 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
[1851] 5 5 5 5 6 7 8 6 7 8 5 5 5 6 6 6 5 7 6 6 6 7 6 5 6 5 7 5 4 5 5 8 5 8 7 5 7
[1888] 5 7 7 6 5 7 7 5 7 6 6 5 5 7 3 3 5 8 6 6 5 5 7 5 6 5 5 5 5 7 6 7 6 6 7 6 5
[1925] 6 5 5 3 6 5 9 5 6 7 7 8 5 4 5 7 6 5 7 7 6 4 6 6 7 6 9 6 5 7 6 5 7 5 6 7 3
[1962] 8 7 7 6 5 5 4 6 8 5 5 5 7 7 6 5 5 6 7 8 8 7 7 6 4 8 9 6 9 6 8 7 5 8 4 7 8
[1999] 6 7 6 8 5 6 7 7 6 5 7 7 6 6 7 5 8 7 6 8 8 6 5 8 6 7 5 7 6 7 4 3 4 7 6 7 6
[2036] 9 5 6 7 7 6 4 7 1 8 6 6 6 5 5 3 5 8 4 5 5 5 6 5 5 7 5 5 7 5 4 7 8 5 6 7 5
[2073] 5 5 7 5 5 7 7 6 5 5 3 7 6 6 6 5 6 5 5 5 5 5 6 5 5 5 5 5 5 5 5 5 5 5 5 5 5
[2110] 5 5 5 5 5 5 7 5 8 6 5 5 5 6 5 7 5 5 5 5 5 5 5 5 5 5 5 7 5 4 6 5 6 5 8 5 5
[2147] 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 7 5 6 5 6 6 5 6 7 6 5 5 5 5 5 5
[2184] 7 3 5 6 6 8 5 7 5 5 6 7 6 7 5 5 7 7 8 7 8 8 5 6 6 7 6 6 7 5 6 6 6 7 5 8 8
[2221] 7 6 5 4 6 6 5 5 5 3 5 7 7 6 7 5 6 7 5 2 5 4 6 6 9 5 5 6 6 5 5 5 5 6 6 6 5
[2258] 6 8 5 5 5 5 5 7 5 5 5 5 5 5 5 5 4 5 5 5 5 5 5 5 4 4 7 5 4 5 6 5 6 3 5 5 6
[2295] 6 7 7 7 3 6 6 7 7 5 6 5 6 5 6 6 5 5 5 5 5 5 5 5 5 5 5 5 5 6 5 5 5 7 5 5 5
[2332] 5 5 5 5 5 5 6 5 5 5 5 7 5 7 5 6 5 5 6 5 6 5 5 6 6 5 6 6 5 5 4 4 5 5 6 5 7
[2369] 5 7 5 5 5 5 7 5 7 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
[2406] 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
[2443] 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
[2480] 5 5 5 5 4 5 4 5 6 6 7 5 6 6 6 6 6 7 6 4 5 5 7 5 5 5 5 5 5 5 5 5 5 5 5 5 5
[2517] 5 6 5 5 5 5 5 6 6 7 6 7 5 6 5 5 5 5 7 5 6 5 7 8 5 6 5 5 7 6 6 6 5 7 7 8 6
[2554] 7 7 7 5 8 6 6 5 3 7 6 6 5 5 3 6 5 4 7 6 6 5 5 6 6 5 6 6 5 8 5 6 6 7 5 6 6
[2591] 5 5 5 6 6 8 7 6 3 8 6 8 4 4 4 8 5 5 5 7 5 5 6 6 7 6 5 8 6 6 4 7 5 5 4 4 4
[2628] 5 6 4 5 5 6 6 5 8 4 6 6 8 7 7 8 8 6 5 7 6 5 8 5 7 7 5 7 8 4 8 2 7 6 4 6 7
[2665] 7 5 9 7 5 3 5 5 7 7 7 6 4 5 7 5 6 7 6 7 6 5 5 5 8 4 5 8 4 6 6 4 8 6 5 5 5
[2702] 4 7 3 5 5 5 8 6 6 7 6 5 7 5 6 6 4 4 5 4 4 5 9 6 6 6 4 7 5 5 5 5 5 8 7 7 8
[2739] 5 6 8 4 5 7 5 3 5 4 5 8 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 6 5 5 5 5 5
[2776] 5 5 5 5 5 5 5 6 6 6 7 7 8 5 5 5 5 5 5 5 5 5 5 5 5 6 5 5 5 5 5 5 5 5 5 5 5
[2813] 5 5 5 5 6 4 5 5 5 4 5 5 5 5 5 5 5 5 5 5 5 7 3 5 3 7 7 4 7 4 5 3 7 8 5 5 6
[2850] 8 5 8 5 8 6 5 4 5 5 7 6 5 7 7 8 7 7 7 6 7 5 5 6 7 4 6 6 5 6 5 3 6 5 5 5 6
[2887] 5 5 5 6 5 5 5 5 6 6 5 5 5 5 5 5 5 3 5 5 5 5 6 6 4 7 5 6 4 5 7 5 5 7 5 5 5
[2924] 5 7 6 5 5 5 5</code></pre>
</div>
</div>
<ol start="4" type="1">
<li>What is the maximum number of Full bathrooms (<code>Full.bath</code>) in this housing data set?</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">max</span>(ames<span class="sc">$</span>Full.Bath)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4</code></pre>
</div>
</div>
<ol start="5" type="1">
<li>Do any houses have more than 2 fireplaces (<code>Fireplaces</code>)? <em>Hint: Use the <code>summary()</code> function.</em></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ames<span class="sc">$</span>Fireplaces)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 0.0000  0.0000  1.0000  0.5993  1.0000  4.0000 </code></pre>
</div>
</div>
<ul>
<li>There are houses that have more than 2 fireplaces.</li>
</ul>
<ol start="6" type="1">
<li>What is the average sale price (<code>price</code>) for houses sold in 2010? (<code>Yr.Sold</code>). Be sure to match the data type of your logical statement with the data type of <code>Yr.Sold</code>. The year should be written as 2010, not “2010”.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(ames<span class="sc">$</span>price[ames<span class="sc">$</span>Yr.Sold<span class="sc">==</span><span class="dv">2010</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 172597.6</code></pre>
</div>
</div>
</section>
<section id="challenge-questions" class="level1">
<h1>Challenge Questions</h1>
<ol type="1">
<li>What is the median <em>price per square foot</em> of houses sold in <em>2008 or later</em>?</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(ames<span class="sc">$</span>price[ames<span class="sc">$</span>Yr.Sold<span class="sc">&gt;=</span><span class="dv">2008</span>] <span class="sc">/</span> ames<span class="sc">$</span>area[ames<span class="sc">$</span>Yr.Sold<span class="sc">&gt;=</span><span class="dv">2008</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 119.4642</code></pre>
</div>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>