{
  "hash": "257ee09a1120d427b0ca9d45408a0892",
  "result": {
    "engine": "knitr",
    "markdown": "# Working with Data Frames\n\nIn this lesson we will learn how to summarize data in a data frame, and to do basic data management tasks such as making new variables, recoding data and dealing with missing data.\n\n:::{.callout-warning icon=false appearance=minimal} \n<a href=\"https://media.csuchico.edu/media/MATH+130+-+Lecture+05A+Intro/1_oifkz4hn\" target=\"_blank\">Section Introduction</a> \n:::\n\n:::{.callout-note title = \"🎓 Learning Objectives\" icon= false}\n\nAfter completing this lesson learners will be able to\n\n-   Summarize variables inside a data frame\n-   Make new variables inside a data frame.\n-   Selectively edit (and recode) data elements.\n-   Identify when data values are missing\n-   Summarize data in the presence of missing values.\n\n:::\n\n:::{.callout-tip title = \"👉 Prepare\" icon=false}\n\n1.  Open your Math 130 R Project. _Forget how to do this? See @sec-rproj._\n2.  Right click and \"save as\" this lessons [[dm_notes.qmd]](notes/dm_notes.qmd) Quarto notes file and save into your `notes/Math130` folder.\n3.  In the *Files* pane, open this Quarto file and Render this file.\n\n:::\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)                    # this came installed with tidyverse\nlibrary(gtsummary)                  # for fancy summary tables\nncbirths <- openintro::ncbirths \n```\n:::\n\n\n\n\n\n[In 2004, the state of North Carolina released to the public a large dataset containing information on births recorded in this state. This dataset has been of interest to medical researchers who are studying the relation between habits and practices of expectant mothers and the birth of their children. The `ncbirths` data frame is a random sample of 1,000 cases from this dataset.]{.aside}\n\nThis first code chunk loads the `ggplot2` package so we can access plotting functions, and then load the `ncbirths` data set, which comes with the `openintro` package.\n\n## Summarizing data\n\n::: {.callout-warning icon=\"false\" appearance=\"minimal\"}\n<a href=\"https://media.csuchico.edu/media/MATH+130+-+Lecture+05A+Summarizing+Data/1_5hztp76z\" target=\"_blank\">Summarizing data section video</a>\n:::\n\nTwo common methods used to summarize data are frequnecy tables for categorical variables (e.g. nominal, ordinal), and summary statistics for numeric (continuous or discrete) variables.\n\n::: {layout-ncol=\"2\"}\n![An illustration of a chick, with text \"Continuous - measured data, can have infinite values within possible range. I am 3.1\" tall, I weight 34.16 grams.\"](img/numeric_data.png){width=\"50%\"}\n\n![An illustrations of a turtle, snail, and butterfly with text \"Nominal - unordered descriptions. \"I'm a turtle! i'm a snail! i'm a butterfly!\"](img/categorical_data.png){width=\"50%\"}\n:::\n\n### Frequency Tables\n\nFrequency tables are used only any type of categorical data (Nominal, ordinal or binary), and the table results show you how many records in the data set have that particular level.\n\nYou can create a basic frequency table by using the `table()` function.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(ncbirths$lowbirthweight)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n    low not low \n    111     889 \n```\n\n\n:::\n:::\n\n\n\n\n\nRelative frequencies (proportions or percentages) are calculated by putting the results of the `table` function inside the `prop_table` function.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.table(\n  table(ncbirths$lowbirthweight)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n    low not low \n  0.111   0.889 \n```\n\n\n:::\n:::\n\n\n\n\n\nThe variable `ncbirths$lowbirthweight` has 111 (11.1%) records with a value of `low`, and 889 (88.9%) records with the value of `not low`.\n\n### Summary Statistics\n\nNumerical variables can be summarized using quantities called *summary statistics* which include the `min`, `max`, `mean` and median. The function `summary()` prints out the five number summary, and includes the mean. This function also displays the number of missing values for that variable.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(ncbirths$visits)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's \n    0.0    10.0    12.0    12.1    15.0    30.0       9 \n```\n\n\n:::\n:::\n\n\n\n\n\nThere are also individual functions available\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# not run\nmean(ncbirths$visits)\nmedian(ncbirths$visits)\nsd(ncbirths$visits)\nmax(ncbirths$visits)\nmin(ncbirths$visits)\n```\n:::\n\n\n\n\n\n### Fancy summary tables\n\nThe `gtsummary` package provides a single function `tbl_summary` to create a really nicely formatted summary table for both quantitative and categorical data types.\n\nThe first argument is the data set, then you `include` the vector of variable that you want to display in the table. By default the sample size *n* and the relative percent are presented for categorical data, and the median, with first and third quartiles shown for quantitiatve data.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntbl_summary(ncbirths, \n            include = c(visits, lowbirthweight)\n            )\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"oooluuknwx\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#oooluuknwx table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#oooluuknwx thead, #oooluuknwx tbody, #oooluuknwx tfoot, #oooluuknwx tr, #oooluuknwx td, #oooluuknwx th {\n  border-style: none;\n}\n\n#oooluuknwx p {\n  margin: 0;\n  padding: 0;\n}\n\n#oooluuknwx .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#oooluuknwx .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#oooluuknwx .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#oooluuknwx .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#oooluuknwx .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#oooluuknwx .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#oooluuknwx .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#oooluuknwx .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#oooluuknwx .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#oooluuknwx .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#oooluuknwx .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#oooluuknwx .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#oooluuknwx .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#oooluuknwx .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#oooluuknwx .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#oooluuknwx .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#oooluuknwx .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#oooluuknwx .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#oooluuknwx .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#oooluuknwx .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#oooluuknwx .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#oooluuknwx .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#oooluuknwx .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#oooluuknwx .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#oooluuknwx .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#oooluuknwx .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#oooluuknwx .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#oooluuknwx .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#oooluuknwx .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#oooluuknwx .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#oooluuknwx .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#oooluuknwx .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#oooluuknwx .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#oooluuknwx .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#oooluuknwx .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#oooluuknwx .gt_left {\n  text-align: left;\n}\n\n#oooluuknwx .gt_center {\n  text-align: center;\n}\n\n#oooluuknwx .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#oooluuknwx .gt_font_normal {\n  font-weight: normal;\n}\n\n#oooluuknwx .gt_font_bold {\n  font-weight: bold;\n}\n\n#oooluuknwx .gt_font_italic {\n  font-style: italic;\n}\n\n#oooluuknwx .gt_super {\n  font-size: 65%;\n}\n\n#oooluuknwx .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#oooluuknwx .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#oooluuknwx .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#oooluuknwx .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#oooluuknwx .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#oooluuknwx .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#oooluuknwx .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#oooluuknwx .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#oooluuknwx div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"label\"><span data-qmd-base64=\"KipDaGFyYWN0ZXJpc3RpYyoq\"><span class='gt_from_md'><strong>Characteristic</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"stat_0\"><span data-qmd-base64=\"KipOID0gMSwwMDAqKg==\"><span class='gt_from_md'><strong>N = 1,000</strong></span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">visits</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">12 (10, 15)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Unknown</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">9</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">lowbirthweight</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    low</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">111 (11%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    not low</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">889 (89%)</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"2\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span> <span data-qmd-base64=\"TWVkaWFuIChRMSwgUTMpOyBuICglKQ==\"><span class='gt_from_md'>Median (Q1, Q3); n (%)</span></span></td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\n\nThe `statistic` argument can be used to change what values are displayed. Here we are specifying we want the mean `{mean}` and standard deviation `{sd}` for all variables that R sees as continuous (numeric), and both the frequency `{n}`, the total number of non-missing values `{N}` and the percent `{p}` for each level of a categorical variable.\n\n\n\n\n\n::: {.cell source-line-numbers='3-6'}\n\n```{.r .cell-code}\ntbl_summary(ncbirths, \n            include = c(visits, lowbirthweight), \n            statistic = list(\n                all_continuous() ~ \"{mean} ({sd})\",\n                all_categorical() ~ \"{n} / {N} ({p}%)\"\n              )\n            )\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"ouyriycozw\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#ouyriycozw table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#ouyriycozw thead, #ouyriycozw tbody, #ouyriycozw tfoot, #ouyriycozw tr, #ouyriycozw td, #ouyriycozw th {\n  border-style: none;\n}\n\n#ouyriycozw p {\n  margin: 0;\n  padding: 0;\n}\n\n#ouyriycozw .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#ouyriycozw .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#ouyriycozw .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ouyriycozw .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ouyriycozw .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ouyriycozw .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ouyriycozw .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ouyriycozw .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#ouyriycozw .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ouyriycozw .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ouyriycozw .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ouyriycozw .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ouyriycozw .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#ouyriycozw .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#ouyriycozw .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ouyriycozw .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ouyriycozw .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ouyriycozw .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ouyriycozw .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ouyriycozw .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#ouyriycozw .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ouyriycozw .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#ouyriycozw .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ouyriycozw .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#ouyriycozw .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ouyriycozw .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ouyriycozw .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ouyriycozw .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#ouyriycozw .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ouyriycozw .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#ouyriycozw .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ouyriycozw .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ouyriycozw .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ouyriycozw .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ouyriycozw .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ouyriycozw .gt_left {\n  text-align: left;\n}\n\n#ouyriycozw .gt_center {\n  text-align: center;\n}\n\n#ouyriycozw .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ouyriycozw .gt_font_normal {\n  font-weight: normal;\n}\n\n#ouyriycozw .gt_font_bold {\n  font-weight: bold;\n}\n\n#ouyriycozw .gt_font_italic {\n  font-style: italic;\n}\n\n#ouyriycozw .gt_super {\n  font-size: 65%;\n}\n\n#ouyriycozw .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#ouyriycozw .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ouyriycozw .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#ouyriycozw .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#ouyriycozw .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#ouyriycozw .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#ouyriycozw .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#ouyriycozw .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#ouyriycozw div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"label\"><span data-qmd-base64=\"KipDaGFyYWN0ZXJpc3RpYyoq\"><span class='gt_from_md'><strong>Characteristic</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"stat_0\"><span data-qmd-base64=\"KipOID0gMSwwMDAqKg==\"><span class='gt_from_md'><strong>N = 1,000</strong></span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">visits</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">12 (4)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Unknown</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">9</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">lowbirthweight</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    low</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">111 / 1,000 (11%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    not low</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">889 / 1,000 (89%)</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"2\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span> <span data-qmd-base64=\"TWVhbiAoU0QpOyBuIC8gTiAoJSk=\"><span class='gt_from_md'>Mean (SD); n / N (%)</span></span></td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\n\n## Missing Data\n\n::: {.callout-warning icon=\"false\" appearance=\"minimal\"}\n<a href=\"https://media.csuchico.edu/media/MATH+130+-+Lecture+05A+Missing+Data/1_3ignf1uh\" target=\"_blank\">Missing data section video</a>\n:::\n\nSometimes the value for a variable is missing. Think of it as a blank cell in an spreadsheet. Missing data can be a result of many things: skip patterns in a survey (i.e. non-smokers don't get asked how many packs per week they smoke), errors in data reads from a machine, researchers skipped a day of data collection for one plant on accident etc.\n\nR puts a `NA` as a placeholder when the value for that piece of data is missing. We can see 4 out of the first 6 values for the variable `fage` (fathers age) in the `ncbirths` data set are missing.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(ncbirths$fage)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] NA NA 19 21 NA NA\n```\n\n\n:::\n:::\n\n\n\n\n\n**Problem 1: `R` can't do arithmetic on missing data.**\n\nSo `5 + NA = NA`, and if you were to try to calculate the `mean()` of a variable, you'd also get `NA`.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(ncbirths$fage)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] NA\n```\n\n\n:::\n:::\n\n\n\n\n\n:::{.callout-tip title = \"👉 Fix this error\" icon=false}\n\nAdd the argument `na.rm=TRUE` to the `mean()` function inside the right hand parenthesis to calculate the mean after excluding missing values.\n\nRun this code chunk interactively to ensure that it works before continuing.\n\n<details>\n  <summary>Solution</summary>\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(ncbirths$fage, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 30.25573\n```\n\n\n:::\n:::\n\n\n\n\n</details>\n\n:::\n\n**Problem 2: Some plots will show `NA` as it's own category**\n\nSometimes this is fine, other times this is undesirable. We'll see later how we can adjust this plot to remove that column of NA.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(ncbirths, aes(premie)) + geom_bar()\n```\n\n::: {.cell-output-display}\n![](dm_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\n\n\n\nMissing values can cause some problems during analysis or undesirable features in a plot so let's see how to detect missing values and how to work around them.\n\n### Identifying missing values\n\nTo find out how many values in a particular variable are missing we can use several different approaches.\n\n#### Look at the raw data {.unnumbered}\n\nWe can look at the raw data using `head()` or opening the data set in the spreadsheet view and skim with our eyes for `NA` values. This may not be helpful if there is no missing values in the first 6 rows, or if there is a large number of variables to look through.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(ncbirths)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 13\n   fage  mage mature    weeks premie visits marital gained weight lowbirthweight\n  <int> <int> <fct>     <int> <fct>   <int> <fct>    <int>  <dbl> <fct>         \n1    NA    13 younger …    39 full …     10 not ma…     38   7.63 not low       \n2    NA    14 younger …    42 full …     15 not ma…     20   7.88 not low       \n3    19    15 younger …    37 full …     11 not ma…     38   6.63 not low       \n4    21    15 younger …    41 full …      6 not ma…     34   8    not low       \n5    NA    15 younger …    39 full …      9 not ma…     27   6.38 not low       \n6    NA    15 younger …    38 full …     19 not ma…     22   5.38 low           \n# ℹ 3 more variables: gender <fct>, habit <fct>, whitemom <fct>\n```\n\n\n:::\n:::\n\n\n\n\n\n#### Look at data summaries {.unnumbered}\n\nFunctions such as `table()` have a `useNA=\"always\"` option to show how many records have missing values, and `summary()` will always show a column for NA.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(ncbirths$habit, useNA=\"always\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nnonsmoker    smoker      <NA> \n      873       126         1 \n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(ncbirths$fage)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's \n  14.00   25.00   30.00   30.26   35.00   55.00     171 \n```\n\n\n:::\n:::\n\n\n\n\n\n#### Use a logical statement {.unnumbered}\n\nThe function `is.na()` returns TRUE or FALSE for each element in the provided vector for whether or not that element is missing.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- c(\"green\", NA, 3)\nis.na(x)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] FALSE  TRUE FALSE\n```\n\n\n:::\n:::\n\n\n\n\n\nIn this example, the vector `x` is created with three elements, the second one is missing. Calling the function `is.na()` on the vector `x`, results in three values, where only the second one is TRUE -- meaning the second element is missing.\n\nThis can be extended to do things such as using the `sum()` function to count the number of missing values in a variable. Here we are *nesting* the functions `is.na()` is written entirely inside the `sum()` function.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(is.na(ncbirths$fage))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 171\n```\n\n\n:::\n:::\n\n\n\n\n\nThere are 171 records in this data set where the age for the father is not present.\n\n:::{.callout-note title = \"Negating `is.na()` to find the non-missing values\"}\nSometimes you want to operate only only the non-missing values. Recall from @sec-logical we can use the `!` to negate a boolean argument. \n:::\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n!is.na(x)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]  TRUE FALSE  TRUE\n```\n\n\n:::\n:::\n\n\n\n\n\nThe first and third values are TRUE - so they are **not** missing.\n\n:::{.callout-tip title = \"👉 Hide the NA bar\" icon=false}\n\nWe can use this tactic to fix that barchart from above. Wrap `!is.na()` around the `premie` variable in the `ggplot` code to create a barchart that does not have a bar for missing values.\n\n<details>\n  <summary>Solution</summary>\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(ncbirths, aes(!is.na(premie))) + geom_bar()\n```\n:::\n\n\n\n\n</details>\n\n:::\n\n## Data management\n\n::: {.callout-warning icon=\"false\" appearance=\"minimal\"}\n<a href=\"https://media.csuchico.edu/media/MATH+130+-+Lecture+05A+Data+Editing+%28Recoding%29/1_kh8v7jk6\" target=\"_blank\">Data editing section video</a>\n:::\n\nSometimes we have a need to create or modify variables in a data frame. You will learn several ways to do this throughout this course, but we will start by using *base R* functions and methods. These are methods that use functions that come with R, not from additional packages.\n\n### Overwrite existing values\n\nChoose all observations (rows) of a `data` set, where a `variable` is equal to some `value`, then set assign `<-` a `new_value` to those rows.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata[data$variable==value] <- new_value  # example code to show syntax.\n```\n:::\n\n\n\n\n\n:::{.callout-tip title = \"Example: Too low birthweight\"}\nLet's look at the numerical distribution of birthweight (in pounds) of the baby.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(ncbirths$weight)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  1.000   6.380   7.310   7.101   8.060  11.750 \n```\n\n\n:::\n:::\n\n\n\n\n:::\n\nThe value of 1 lb seems very low. The researchers you are working with decide that is a mistake and should be excluded from the data. We would then set all records where `weight=1` to missing.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nncbirths$weight[ncbirths$weight==1] <- NA\n```\n:::\n\n\n\n\n\nCode explainer:\n\n-   The specific variable `ncbirths$weight` is on the left side outside the `[]`. So just the variable `weight` is being changed.\n-   Recall that bracket notation `[]` can be used to select rows where a certain logical statement is true. So `[ncbirths$weight==1]` will only show records where `weight` is equal to 1.\n-   Notice where the assignment arrow (`<-`) is at. This code assigns the value of `NA` (missing) to the variable `weight`, where `weight==1`.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmin(ncbirths$weight, na.rm=TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.19\n```\n\n\n:::\n:::\n\n\n\n\n\nThe minimum weight is now 1.19.\n\n:::{.callout-tip title = \"👉 Your Turn\" icon=false}\nBut what about other weights that aren't quite as low as 1, but still unusually low?\n\n-   Write the code to set all birth weights less than 4 lbs (`<4`) to missing (NA).\n-   Then recalculate the mean to confirm your recode worked.\n\n<details>\n\n<summary>Solution</summary>\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nncbirths$weight[ncbirths$weight < 4] <- NA\nmin(ncbirths$weight, na.rm=TRUE)\n```\n:::\n\n\n\n\n\n</details>\n:::\n\n\n### Creating new variables\n\n::: {.callout-warning icon=\"false\" appearance=\"minimal\"}\n<a href=\"https://media.csuchico.edu/media/MATH+130+-+Lecture+05A+Creating+New+Variables/1_ivmj78et\" target=\"_blank\">Creating new variables section video</a>\n:::\n\n:::{.callout-important title = \"New variables should be added to the data frame\"}\n\nThis can be done in base R using `$` sign notation. \n:::\n\nThe new variable you want to create goes on the left side of the assignment operator `<-`, and how you want to create that new variable goes on the right side.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata$new_variable <- creation_statement  # example code not run\n```\n:::\n\n\n\n\n\n:::{.callout-tip title = \"Example: Row-wise difference between two existing variables\"}\n\nAs a pregnancy progresses, both the mother and the baby gain weight. The variable `gained` is the total amount of weight the mother gained in her pregnancy. The variable `weight` is how much the baby weighed at birth.\n\n:::\n\n\nThe following code creates a new variable `wtgain_mom` the weight gained by the mother, that is not due to the baby by subtracting `weight` from `gained`. Note all variables are prefaced with `$`, denoting that they exist inside the `ncbirths` data set.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nncbirths$wtgain_mom <- ncbirths$gained - ncbirths$weight\n```\n:::\n\n\n\n\n\nTo confirm this variable was created correctly, we look at the data contained in three variables in question.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(ncbirths[,c('gained', 'weight', 'wtgain_mom')])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 3\n  gained weight wtgain_mom\n   <int>  <dbl>      <dbl>\n1     38   7.63       30.4\n2     20   7.88       12.1\n3     38   6.63       31.4\n4     34   8          26  \n5     27   6.38       20.6\n6     22   5.38       16.6\n```\n\n\n:::\n:::\n\n\n\n\n\n:::{.callout-important title = \"Trust but Verify\"}\nIt's always important to visually confirm that the code you wrote actually had the intended effect.\n\n:::\n\n\n### Dichtomizing data\n\nThe `ifelse()` is hands down the easiest way to create a binary variable (dichotomizing, only 2 levels)\n\nLet's add a variable to identify if a mother in the North Carolina births data set was underage at the time of birth. Specifically Make a new variable `underage` on the `ncbirths` data set. If `mage` is under 18, then the value of this new variable is `underage`, else it is labeled as `adult`.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nncbirths$underage <- ifelse(ncbirths$mage < 18, \"underage\", \"adult\")\n```\n:::\n\n\n\n\n\nCode explainer:\n\n-   The function is `ifelse()` - one word.\n-   The arguments are: `ifelse(logical, value if TRUE, value if FALSE)`\n    -   The `logical` argument is a statement that resolves as a `boolean` variable, as either TRUE or FALSE.\n    -   The second argument is what you want the resulting variable to contain if the logical argument is `TRUE`.\n    -   The last argument is what you want the resulting variable to contain if the logical argument is `FALSE`.\n\n**Trust but Verify**\n\nFirst let's look at the frequency table of `underage` and see if records exist with the new categories, and if there are any missing values.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(ncbirths$underage, useNA=\"always\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n   adult underage     <NA> \n     963       37        0 \n```\n\n\n:::\n:::\n\n\n\n\n\nNext let's check it against the value of `mage` itself. Let's look at all rows where mothers age is either 17 or 18 `mage %in% c(17,18)`, and only the columns of interest.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nncbirths[ncbirths$mage %in% c(17,18),c('mage', 'underage')]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 57 × 2\n    mage underage\n   <int> <chr>   \n 1    17 underage\n 2    17 underage\n 3    17 underage\n 4    17 underage\n 5    17 underage\n 6    17 underage\n 7    17 underage\n 8    17 underage\n 9    17 underage\n10    17 underage\n# ℹ 47 more rows\n```\n\n\n:::\n:::\n\n\n\n\n\nNotice I snuck a new operator in on you - `%in%`. This is a way you can provide a list of values (a.k.a a vector) and say \"if the value of the variable I want is %in% any of these options in this vector...\" do the thing.\n\n## Chaining commands\n\n::: {.callout-warning icon=\"false\" appearance=\"minimal\"}\n<a href=\"https://media.csuchico.edu/media/MATH+130+-+Lecture+05A+Chaining+Using+the+Pipe+E/1_chcscua0\" target=\"_blank\">Chaining commands section video</a>\n:::\n\nTwo common styles:\n\n-   `|>` This is the \"native\" pipe that's built into R.\n-   `%>%` This pipe is loaded with the `tidyverse` package.\n\nThey both function the same, but you'll see both being used so it's good to know that they both exist. That way if you are not using other functions from the `tidyverse`, you can still enjoy the chaining functionality.\n\n### What is \"Chaining\"?\n\nThe pipe lets you string set of functions together, like links on a chain, to be completed in the order specified. This works with the majority of functions, specifically when the result of the function is a data frame, a vector, or sometimes the results of a model.\n\n> \"and then....\"\n\nThis is what I read to myself when using the pipe. \"Do this `|>` the next thing `|>` do this third thing `|>` this last\"\n\n:::{.callout-tip title = \"👉Example: Frequency tables & summary statistics using the pipe\" icon=false}\n\nFirst stating the variable, then pipe in the summary function.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nncbirths$mature |> table() # instead of table(ncbirths$mature)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n mature mom younger mom \n        133         867 \n```\n\n\n:::\n\n```{.r .cell-code}\nncbirths$mage |> mean() #instead of mean(ncbirths$mage)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 27\n```\n\n\n:::\n:::\n\n\n\n\n\n:::\n\nThese can be read as\n\n1.  Get the `mature` variable from the `ncbirths` data set\n2.  *and then* create a frequency table on that variable\n\nand\n\n1.  Get the `mage` variable from the `ncbirths` data set\n2.  *and then* calculate the mean of that variable\n\nThese may be trivial examples now but the usefulness of this approach will be apparent before the class is finished.\n\n:::{.callout-important title = \"Behind the scenes\"}\n\nWhat actually is happening, is that the result from the code on the left of the `|>` gets passed into the first argument of the commands on the right hand side. Two things to keep in mind: \n\n\n:::: {.columns}\n::: {.column width=\"45%\"}\n1. Do not include the variable on both sides.\n\n```         \nncbirths$mature |>  ✅\n  table()    \n  \nncbirths$mature |> \n  table(ncbirths$mature) ❌\n```\n:::\n\n::: {.column width=\"10%\"}\n:::\n\n::: {.column width=\"45%\"}\n2. the pipe itself must be at the end of a \"sentence\".\n\n```         \nncbirths$mature |>   ✅\n  table()\n\nncbirths$mature      ❌\n|> table()\n```\n:::\n::::\n\n:::\n",
    "supporting": [
      "dm_files/figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}