{
  "hash": "a7082ec8bb69879c934312114e62d788",
  "result": {
    "engine": "knitr",
    "markdown": "# Working with Data\n\n\nIn this lesson we will learn how to summarize data in a data frame, and to do basic data management tasks such as making new variables, recoding data and dealing with missing data. <a href=\"https://media.csuchico.edu/media/MATH+130+-+Lecture+05A+Intro/1_oifkz4hn\" target=\"_blank\">(Introduction Video)</a>\n\n::: .callout-note\n### Learning Objectives\n\nAfter completing this lesson learners will be able to\n\n* Summarize variables inside a data frame\n* Make new variables inside a data frame. \n* Selectively edit (and recode) data elements. \n* Identify when data values are missing\n* Summarize data in the presence of missing values.\n\n:::\n\n\n### Preparation \n\nPrior to this lesson learners should\n\n* Download the [[05_dm_notes.Rmd]](05_dm_notes.Rmd) R markdown file and save into your `notes/Math130` folder. \n    - Open this in RStudio and ensure the first code chunk will run without error. \n* Install the `ggplot2`, `openintro` and `dplyr` packages ([this was done as part of lesson 02](https://norcalbiostat.github.io/MATH130/notes/02_setup_slides.html#19)). \n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\nlibrary(ggplot2)\nncbirths <- openintro::ncbirths\n```\n:::\n\n\n\n\n\n\n\n## Missing Data <a href=\"https://media.csuchico.edu/media/MATH+130+-+Lecture+05A+Missing+Data/1_3ignf1uh\" target=\"_blank\">(Video)</a>\n\nMissing data occurs when the value for a variable is missing. Think of it as a blank cell in an spreadsheet. Missing values can cause some problems during analysis, so let's see how to detect missing values and how to work around them. \n\nConsider the `ncbirths` data set, specifically the first column containing data on the father's age (`fage`).\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(ncbirths)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 x 13\n   fage  mage mature    weeks premie visits marital gained weight lowbirthweight\n  <int> <int> <fct>     <int> <fct>   <int> <fct>    <int>  <dbl> <fct>         \n1    NA    13 younger ~    39 full ~     10 not ma~     38   7.63 not low       \n2    NA    14 younger ~    42 full ~     15 not ma~     20   7.88 not low       \n3    19    15 younger ~    37 full ~     11 not ma~     38   6.63 not low       \n4    21    15 younger ~    41 full ~      6 not ma~     34   8    not low       \n5    NA    15 younger ~    39 full ~      9 not ma~     27   6.38 not low       \n6    NA    15 younger ~    38 full ~     19 not ma~     22   5.38 low           \n# i 3 more variables: gender <fct>, habit <fct>, whitemom <fct>\n```\n\n\n:::\n:::\n\n\n\n\n\n\n* R puts a `NA` as a placeholder when the value for that piece of data is missing. \n* Missing data can be a result of many things: skip patterns in a survey (i.e. non-smokers don't get asked how many packs per week they smoke), errors in data reads from a machine, etc. \n\n\n**Problem 1** \n`R` can't do arithmetic on missing data. So `5 + NA = NA`, and if you were to try to calculate the `mean()` of a variable, you'd also get `NA`. \n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(ncbirths$fage)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] NA\n```\n\n\n:::\n:::\n\n\n\n\n\n\n**Problem 2**\nSome plots will show `NA` as it's own category, which is undesirable. \n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(ncbirths, aes(premie))+geom_bar()\n```\n\n::: {.cell-output-display}\n![](dm_files/figure-pdf/unnamed-chunk-4-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\n\n### Identifying missing values \n\nTo find out how many values in a particular variable are missing we can use one of two approaches:  \n\n1. Look at the raw data using `head()` or `str()`. This may not be helpful if there is no missing values in the first 6 rows, or if there is a large number of variables to look through. \n2. Look at data summaries using `table()` for categorical data and `summary()` for numerical data. In the examples below you can see that entries for \"NA\" are included in the output. \n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(ncbirths$habit, useNA=\"always\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nnonsmoker    smoker      <NA> \n      873       126         1 \n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(ncbirths$fage)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's \n  14.00   25.00   30.00   30.26   35.00   55.00     171 \n```\n\n\n:::\n:::\n\n\n\n\n\n\n### Is it NA?\n\nThe function `is.na()` returns TRUE or FALSE for each element in the provided vector for whether or not that element is missing.  \n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- c(\"green\", NA, 3)\nis.na(x)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] FALSE  TRUE FALSE\n```\n\n\n:::\n:::\n\n\n\n\n\n\nIn this example, the vector `x` is created with three elements, the second one is missing. Calling the function `is.na()` on the vector `x`, results in three values, where only the second one is TRUE -- meaning the second element is missing. \n\nThis can be extended to do things such as using the `sum()` function to count the number of missing values in a variable. Here we are _nesting_ the functions `is.na()` is written entirely inside the `sum()` function. \n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(is.na(ncbirths$fage))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 171\n```\n\n\n:::\n:::\n\n\n\n\n\n\nThere are 171 records in this data set where the age for the father is not present. \n\n\n## Summarizing data <a href=\"https://media.csuchico.edu/media/MATH+130+-+Lecture+05A+Summarizing+Data/1_5hztp76z\" target=\"_blank\">(Video)</a>\n\nTwo common methods used to summarize data are `table()` for categorical factor variables, and `summary()` for numeric variables. \n\n## Frequency Tables for categorical data\nFrequency tables are used only on categorical data, and the table results show you how many records in the data set have that particular factor level. \n\nYou can create a frequency table by using the `table()` function. The `useNA=\"always\"` argument tells `R` to always include an entry for missing values `<NA>`, even if there are none. \n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(ncbirths$lowbirthweight, useNA=\"always\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n    low not low    <NA> \n    111     889       0 \n```\n\n\n:::\n:::\n\n\n\n\n\n\nThe variable `ncbirths$lowbirthweight` has 111 records with a value of `low`, and 889 records with the value of `not low`. \n\n### Summary statistics for numerical data\nNumerical variables can be summarized using statistics such as the min, max, mean and median. The function `summary()` prints out the five number summary, and includes the mean. This function also displays the number of missing values for that variable. \n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(ncbirths$visits)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's \n    0.0    10.0    12.0    12.1    15.0    30.0       9 \n```\n\n\n:::\n:::\n\n\n\n\n\n\nMothers included in this data set visited the doctor on average 12.1 times during their pregnancy. \n\n\n## Data editing / Recoding <a href=\"https://media.csuchico.edu/media/MATH+130+-+Lecture+05A+Data+Editing+%28Recoding%29/1_kh8v7jk6\" target=\"_blank\">(Video)</a>\n\n\nSometimes we have a need to edit, or change data. We can change values of existing data by using logical statements.\n\nTo choose all observations (rows) of a `data` set, where a `variable` is equal to some `value`, you would type\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata[data$variable==value]  # example code\n```\n:::\n\n\n\n\n\n\nWe can use this method of selecting rows, to change data in those specific rows. \n\n\n**Example 1: Too low birthweight**\n\nLet's look at the numerical distribution of birthweight of the baby. \n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(ncbirths$weight)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  1.000   6.380   7.310   7.101   8.060  11.750 \n```\n\n\n:::\n:::\n\n\n\n\n\n\nThe value of 1 lb seems very low. The researchers you are working with decide that is a mistake and should be excluded from the data. We would then set all records where `weight=1` to missing. \n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nncbirths$weight[ncbirths$weight==1] <- NA\n```\n:::\n\n\n\n\n\n\n* The specific variable `ncbirths$weight` is on the left side outside the `[]`. So just the variable `weight` is being changed. * Recall that bracket notation `[]` can be used to select rows where a certain logical statement is true. So `[ncbirths$weight==1]` will only show records where `weight` is equal to 1. \n* Notice where the assignment arrow (`<-`) is at. This code assigns the value of `NA` (missing) to the variable `weight`, where `weight==1`. \n\n\nBut what about other weights that aren't quite as low as 1, but still unusually low? The boxplot below shows outlying values as dots on the low end of birthweight. \n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nboxplot(ncbirths$weight)\n```\n\n::: {.cell-output-display}\n![](dm_files/figure-pdf/unnamed-chunk-13-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\nLet's set all birth weights less than 4 lbs to missing. \n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nncbirths$weight[ncbirths$weight < 4] <- NA\n```\n:::\n\n\n\n\n\n\nIt is important to plot the data again, to make sure that there are no values below 4 now. \n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nboxplot(ncbirths$weight)\n```\n\n::: {.cell-output-display}\n![](dm_files/figure-pdf/unnamed-chunk-15-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\n\n## Creating new variables <a href=\"https://media.csuchico.edu/media/MATH+130+-+Lecture+05A+Creating+New+Variables/1_ivmj78et\" target=\"_blank\">(Video)</a>\n\n**New variables should be added to the data frame.** This can be done using `$` sign notation. \n\nThe new variable you want to create goes on the left side of the assignment operator `<-`, and how you want to create that new variable goes on the right side. \n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata$new_variable <- creation statement\n```\n:::\n\n\n\n\n\n\n::: .callout-tip\n### Example: Row-wise difference between two existing variables\n\nAs a pregnancy progresses, both the mother and the baby gain weight. The variable `gained` is the total amount of weight the mother gained in her pregnancy. The variable `weight` is how much the baby weighed at birth.\n\n:::\n\nThe following code creates a new variable `wtgain_mom` the weight gained by the mother, that is not due to the baby by subtracting `weight` from `gained`.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nncbirths$wtgain_mom <- ncbirths$gained - ncbirths$weight\n```\n:::\n\n\n\n\n\n\nTo confirm this variable was created correctly, we look at the data contained in three variables in question. \n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(ncbirths[,c('gained', 'weight', 'wtgain_mom')])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 x 3\n  gained weight wtgain_mom\n   <int>  <dbl>      <dbl>\n1     38   7.63       30.4\n2     20   7.88       12.1\n3     38   6.63       31.4\n4     34   8          26  \n5     27   6.38       20.6\n6     22   5.38       16.6\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n### Dichtomizing data \n\nThe `ifelse()` is hands down the easiest way to create a binary variable (dichotomizing, only 2 levels)\n\nLet's add a variable to identify if a mother in the North Carolina births data set was underage at the time of birth. \n\n* We will define this as if the mothers age `mage` is under 18. \n* We will create a new factor variable with two values: `underage` and `adult`. \n* We will use the `ifelse()` function. \n    - It's set of arguments are: `ifelse(logical, value if TRUE, value if FALSE)`\n    - The `logical` argument is a statement that resolves as a `boolean` variable, as either TRUE or FALSE.\n    - The second argument is what you want the resulting variable to contain if the logical argument is `TRUE`\n    - The last argument is what you want the resulting variable to contain if the logical argument is `FALSE`\n\nMake a new variable `underage` on the `ncbirths` data set. If `mage` is under 18, then the value of this new variable is `underage`, else it is labeled as `adult`. \n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nncbirths$underage <- ifelse(ncbirths$mage < 18, \"underage\", \"adult\")\n```\n:::\n\n\n\n\n\n\nYou should always make sure your code works as intended.\n\n* First let's look at the frequency table of `underage` and see if records exist with the new categories, and if there are any missing values. \n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(ncbirths$underage, useNA=\"always\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n   adult underage     <NA> \n     963       37        0 \n```\n\n\n:::\n:::\n\n\n\n\n\n* Next let's check it against the value of `mage` itself. Let's look at all rows where mothers age is either 17 or 18 `mage %in% c(17,18)`, and only the columns of interest. \n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nncbirths[ncbirths$mage %in% c(17,18),c('mage', 'underage')]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 57 x 2\n    mage underage\n   <int> <chr>   \n 1    17 underage\n 2    17 underage\n 3    17 underage\n 4    17 underage\n 5    17 underage\n 6    17 underage\n 7    17 underage\n 8    17 underage\n 9    17 underage\n10    17 underage\n# i 47 more rows\n```\n\n\n:::\n:::\n\n\n\n\n\n\nNotice I snuck a new operator in on you - `%in%`. This is a way you can provide a list of values (a.k.a a vector) and say \"if the value of the variable I want is %in% any of these options in this vector...\" do the thing. \n\n\n## Chaining using the pipe <a href=\"https://media.csuchico.edu/media/MATH+130+-+Lecture+05A+Chaining+Using+the+Pipe+E/1_chcscua0\" target=\"_blank\">(Video)</a>\n\n![](../static/img/pipe.png)\n\n\nThe pipe is technically part of the `magrittr` package, but quite often we will use it in conjunction with functions from the `dplyr` package introduced in a later lesson. In fact it's so commonly used with `dplyr` functions that it the `magrittr` package is loaded when you load `dplyr` (which is what we do here). However, the pipe operator is so useful in many other places that it deserves it's own introduction here. \n\n> \"and then....\"\n\nThis is what I read to myself when using the pipe (`%>%`). The pipe lets you chain functions together, as long as the first argument of the function is a `data.frame` or a variable in a `data.frame`. \n\n### Example: Frequency tables & summary statistics\n\nEarlier we saw that to create a frequency table for categorical variable we can type: \n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(ncbirths$mature)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n mature mom younger mom \n        133         867 \n```\n\n\n:::\n:::\n\n\n\n\n\n\nThis is also accomplished by first stating the variable, then piping in the summary function. \n\n> If you get an error message saying something like <span style=\"color:red;\">function not found</span>, that is a message to you that you need to load the library. See the [preparation](#preparation) section of these notes to remind yourself how to do this. \n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nncbirths$mature %>% table()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n.\n mature mom younger mom \n        133         867 \n```\n\n\n:::\n\n```{.r .cell-code}\nncbirths$mage %>% mean()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 27\n```\n\n\n:::\n:::\n\n\n\n\n\n\nI read this as \"Take the `mage` variable on the `ncbirths` data set, _and then_ calculate the mean.\"\n\nThe pipe `%>%` allows multiple steps to be chained together to execute a series of commands all at once. \nThe usefulness of this approach will be apparent before the class is finished. \n\n\n",
    "supporting": [
      "dm_files/figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}